### ISSUE TITLE
Source fieldtype saves empty field reference

### ISSUE THREAD

**Issue by jesseleite** [statamic/seo-pro#126]
If you select `field` and don't enter a field handle, it'll still save:

```
image: '@seo:'
```

Which will cause undefined index when rendering meta.

**Comment by fitzage** [comment]
For additional data, I think this only causes undefined index if you then configure an asset container in the SEO Pro config. 

Once you do this, Statamic or SEO Pro sees this erroneous image field and generates a file named `.yaml` in the `.meta` folder of the selected asset container. This doesn’t contain the necessary metadata fields (because there’s no actual image to create them from), so it prompts the undefined index error.

**Comment by jesseleite** [comment]
The source fieldtype is used for more than just social images (ie. on the SEO `title` or `description` etc), so the undefined index would happen elsewhere as well.

**Comment by jesseleite** [comment]
Fixed in next version.
