### ISSUE TITLE
Publish meta view

### ISSUE THREAD

**Issue by curtisblackwell** [statamic/seo-pro#134]
You can currently publish the views for the sitemap and humans.txt, but not the meta view.

I'm seeing issues where the canonical URL is incorrect (either flat out doesn't even match the current URL or includes query parameters, [which is apparently controversial](https://discordapp.com/channels/489818810157891584/489827080196980739/594352898448687126)).

Rather than attempt a one-size-fits-all solution, allowing us to publish the meta view would allow us to better customize to suit our needs.

**Comment by jesseleite** [comment]
It was intentional that we didn't make the meta view publishable.

The sitemap and humans views are small and unlikely to be changed much as we release SEO Pro updates, so if the user publishes them, their app isn't likely to break when we tag SEO Pro updates.

The meta view deals with a butt ton of data being passed into it, and a lot more rendering logic compared to the other publishable views.  If we release an update that changes how data is passed or rendered, people are going to have to keep their meta view in sync with ours.  Imagine they published the generated views to customize their humans.txt view, but didn't touch the published meta view, their meta view will take precedence as we tag SEO Pro updates.

I wonder if there is a better way to handle canonical URL problems?

**Comment by jesseleite** [comment]
Jason had a good point.  You can override your canonical URL by using a view composer...

```php
View::composer('seo-pro::meta', function ($view) {
    $view->with('canonical_url', 'https://jeffbezos.com');
});
```

Does that solve your issue?

**Comment by curtisblackwell** [comment]
That should work for me. I'll give it a go today.

It does feel like there's a better solution to be discovered, though. Statamic attracts plenty of people who don't write PHP and this is a paid, first-party SEO addon. I imagine most people would expect control over things as important as canonical links. I thought v2's version allowed control over this, too… maybe it was via a field in the entry forms?

**Comment by jasonvarga** [comment]
If the canonical url is incorrect, let's address that instead of needing you to override the view.

**Comment by curtisblackwell** [comment]
Well, there's both the one incorrect one I found and those that include query parameters, so it sounds like both might be necessary.

It looks like the ones defined in `routes/web.php` always just use the homepage URL. Here's one example:

```php
Route::statamic('/blog/search', 'blog_posts.search-results.index');
// <link href="http://highland.test" rel="canonical" />
```

**Comment by curtisblackwell** [comment]
This is what I'm using:

```php
```

**Comment by curtisblackwell** [comment]
This is what I'm using to get the behavior I need:

```php
View::composer('seo-pro::meta', function ($view) {
    $view->with('canonical_url', request()->url());
});
```
