### ISSUE TITLE
PHP 8 support

### ISSUE THREAD

**Issue by luisdalmolin** [statamic/seo-pro#185]
Hi there, 

First of all, thanks for this nice library. It seems this library is not compatible with PHP 8? After upgrading my project, I'm getting the following error:

```
TypeError
method_exists(): Argument #1 ($object_or_class) must be of type object|string, null given
```

This happens on this file/line: `vendor/statamic/seo-pro/src/Cascade.php:261`. I believe a new check if `$this->model` exists would be needed in there before calling the `method_exists`.

**Comment by jesseleite** [comment]
Hmm, I'm having trouble reproducing this with PHP8. Which route(s) are you experiencing this on? Also, could you paste the output of `php please support:details`?

**Comment by luisdalmolin** [comment]
Sure, here it is:

Statamic 3.1.29 Pro
Laravel 8.51.0
PHP 8.0.8
statamic/eloquent-driver 0.1.1
statamic/seo-pro 2.2.1

One of the pages this is failing is /cp/seo-pro/section-defaults/collections/blog/edit, which is a custom collection we have.

**Comment by jesseleite** [comment]
Hey @luisdalmolin, Still having trouble reproducing this. Not sure if you're able to send us a zip of a site where you're experiencing this? Thanks!

**Comment by luisdalmolin** [comment]
@jesseleite I'll not be able to send you a zip of our project, but I'll try to get you a repo with the issue happening

**Comment by jesseleite** [comment]
@luisdalmolin Totally understandable. Even a fresh statamic site repo with the issue reproduced would be super helpful, thanks!

**Comment by Orrison** [comment]
Hey @jesseleite, I work with @luisdalmolin and have created a fresh statamic site repo that reproduces this issue.
That repo can be found [here](https://github.com/kirschbaum-development/seo-pro-bug)

Here is an output of my support details:
```
Statamic 3.1.32 Solo
Laravel 8.52.0
PHP 8.0.9
statamic/eloquent-driver 0.1.1
statamic/seo-pro 2.2.1
```

So the key issue I discovered is that the issue is with ANY collection, not just our custom one. So the default `Page` collection triggers it.
And that it seems to be a conflict with `statamic/seo-pro` AND `statamic/eloquent-driver` as the error only happens when both are installed and setup.
The error does not happen with `statamic/seo-pro` installed alone.

Both plugins are setup with their default settings to reproduce this error.

**Comment by jesseleite** [comment]
Hey thank you @Orrison for taking the time to create a repo. I didn't make the connection that it was a conflict with SEO Pro and the Eloquent driver; Will definitely take a look thanks!

**Comment by jesseleite** [comment]
@Orrison Dang, the fix should be easy, but even with your repo I'm struggling to reproduce that `method_exists()` error 😥  I'm sure this bug is real, but it's being elusive! Anyway, what else could be different between our setups? Here's what I'm seeing:

```
Statamic 3.1.32 Pro
Laravel 8.52.0
PHP 8.0.8
statamic/eloquent-driver 0.1.1
statamic/seo-pro 2.2.1
```

![CleanShot 2021-07-30 at 18 19 11](https://user-images.githubusercontent.com/5187394/127717056-4af3274d-996d-4e2e-8509-f942b4345167.png)

![CleanShot 2021-07-30 at 18 22 06](https://user-images.githubusercontent.com/5187394/127717266-c3fed30b-bf3f-43a1-b1fd-67a6dee26fc5.png)

![CleanShot 2021-07-30 at 18 20 25](https://user-images.githubusercontent.com/5187394/127717152-00366c84-8d0e-4575-be06-a8d95111464a.png)

![CleanShot 2021-07-30 at 18 20 49](https://user-images.githubusercontent.com/5187394/127717160-fd3889c7-dee6-477b-b8a9-a77a7b196082.png)

**Comment by Orrison** [comment]
Hey @jesseleite,

So our setups are almost identical. Then I noticed that you have rows in your `entries` table but I do not. I wonder if this is because a default `/` page may be created when you first setup that I had deleted at some point.

So I DO get the error with this setup if my `entries` table is completely empty. But if I manually put in a row into that table I no longer get the error.

Try deleting those entries from your table and see if you get the error then.

**Comment by Orrison** [comment]
@jesseleite I did a little more investigating and have discovered that the real issue is when you do NOT have a record in the `entries` table with a `uri` of `/`.

This is because in `vendor/statamic/seo-pro/src/Cascade.php@57`, it calls `Entry::findByUri('/')` which would be `null`. This means `$this->model` would never be set, causing issues at`vendor/statamic/seo-pro/src/Cascade.php:261` and further down in the calls where `this->model` is used.

So the difference in our setups, and why you are not seeing this error on your end, is because you have a record in `entries` with a `uri` of `/`. You could see this error by deleting it.

**Comment by jesseleite** [comment]
@Orrison Oh the `Entry::findByUri('/')` is the key I was missing, thanks for looking into this!

**Comment by jesseleite** [comment]
@Orrison @luisdalmolin See above fix. Maybe you can give it a whirl, see if you run into any other bugs with Eloquent before we tag this?

PS. Are you intentionally not adding a home page with a route of `/`?

**Comment by luisdalmolin** [comment]
@jesseleite Yes, we are using Statamic for the blog mainly, so we only have a `/blog` and then the blog entries.

**Comment by Orrison** [comment]
> @Orrison @luisdalmolin See above fix. Maybe you can give it a whirl, see if you run into any other bugs with Eloquent before we tag this?
> 
> PS. Are you intentionally not adding a home page with a route of `/`?

Sure thing, I will copy that change down and test to see if I notice any issues.

**Comment by Orrison** [comment]
@jesseleite tested and it all seems to be working fine. Thanks!

**Comment by jesseleite** [comment]
Thanks again, will tag soon.
