### ISSUE TITLE
Performance

### ISSUE THREAD

**Issue by stuartcusackie** [statamic/seo-pro#218]
I'm optimising a website today and running measures with DebugBar.

I am finding the seo-pro meta tag to be one of the biggest contributors to page load times. I'm using Blade but it seems to be the same with the Antlers version.

Without any tags my head renders very fast - 2ms

Once I add the `@seo_pro('meta')` tag to the header the timing jumps up to between 500-600ms.

This is how I am testing:
```
{{ Debugbar::startMeasure('render_head', 'Render head') }}
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="csrf-token" content="{{ csrf_token() }}">
        <link rel="stylesheet" href="{{ mix('css/site.css') }}">
        <script src="{{ mix('js/site.js') }}" defer></script>
        @livewireStyles
    </head>
  {{ Debugbar::stopMeasure('render_head') }}
```

This isn't a problem once I enable the static cache but I'm just wondering if there's any way to improve it. Perhaps meta data can be cached or something?

Thanks!

**Comment by jasonvarga** [comment]
> Without any tags my head renders very fast - 2ms
> Once I add the @seo_pro('meta') tag to the header the timing jumps up to between 500-600ms.

I would expect the view to render super quickly if you're basically not doing anything.
When you add the tag/directive, now it'll actually do stuff, so I'd expect the render time to increase.

The tag is doing a fair bit of work, compiling data from the current entry, merging fallbacks from various places, doing augmentation, etc.

I'm sure it could be improved, and we will of course aim to do so, but I'll close this for now since it's not a bug, and "improve performance" would be an issue that could just be open forever.
