### ISSUE TITLE
FR: ability to set canonical url

### ISSUE THREAD

**Issue by lukeagsmith** [statamic/seo-pro#25]

**Comment by jackmcdade** [comment]
They're already set automatically based on your Permalink.

**Comment by ArondeParon** [comment]
@jackmcdade we're experiencing issues with this as well. Isn't the idea of canonical urls to be able to set them to something _different_ than the current permalink?

We have tried overriding the values, but there currently does not seem to be a way to do this because `TagData.php` will simply set it to the absolute URL again.

Possible solutions would be:

- allow the tag to accept context, that is automatically merged in `TagData.php`
Example:
```php
{{ seo_pro:meta canonical_url='/foo' }}
```

- allow the canonical URL to be set through the CP, just like the title and description can be set. This seems to be the best solution.

Would love to hear your thoughts on this, because as it is now, the canonical URL functionality is not really usable. If I am overlooking something, I'd very much like to hear it too.

Thanks.

**Comment by jasonvarga** [comment]
Can you explain in more detail why you are trying to set the canonical URL to something else? Do you mean you want to do it on a couple of pages or for the entire site?

**Comment by ArondeParon** [comment]
@jasonvarga thanks for getting back to me.

We have two collections on our website. The main difference between the two is the URL. We are using separate URLs for different targeting campaigns (short urls for print campaigns, longer urls for Adwords, for example).

The canonical tag is essential to make sure the two pages are not treated as duplicate content.

Adding a canonical tag to a singular page (which is how it works now) does not really add value. The exact reason for the canonical tag is to refer to _other_ pages so that the page which is being referred to can be treated as the original source.

This is a pretty common SEO case, so I believe it would probably be best to expose the controls for this property in the SEO tab in the CP.

For now, we have created our own hotfix by creating our own Seo tag that extends `SeoProTags` as follows:

```php
class SeoTags extends SeoProTags
{
    public function meta()
    {
        if (array_get($this->context, 'seo') === false) {
            return;
        }

        $data = (new TagData)
            ->with(Settings::load()->get('defaults'))
            ->with(array_get($this->context, 'seo', []))
            ->withCurrent(array_get($this->context, 'page_object'))
            ->get();

        $canonical = $this->getParam('canonical');

        if ($canonical !== null) {
            $canonicalEntry = Entry::find($canonical);
            if ($canonicalEntry) {
                $data['canonical_url'] = $canonicalEntry->absoluteUrl();
            }
        }

        return $this->render('meta', $data);
    }
}
```

Our non-canonical pages have a collection field in which the UUID of the canonical page is stored, so we call it like this: `{{ seo:meta canonical=parent }}`

**Comment by fitzage** [comment]
Can I at least disable the canonical URL feature in SEO Pro so I can build my own?

Here's our issue: we have some blog articles that have been turned into documentation pages. If people google the content, we want Google to know that the documentation page is the correct page, but redirecting the blog article would be a jarring user experience.

There's also the occasional cross-posted blog article where a partner may author an article that we also want to include on our site, but we want google to know the original copy is the canonical version.

So really, in some cases just redirecting the page makes the most sense, but sometimes setting the canonical URL is the best experience for the user.
