### ISSUE TITLE
Runway support?

### ISSUE THREAD

**Issue by sebabal** [statamic/seo-pro#360]
Does SEO Pro support runway models? Or maybe any documentation to extend SEO Pro to support it?

**Comment by duncanmcclean** [comment]
No, it doesn't.

**Comment by amadeann** [comment]
@duncanmcclean 
I just started experimenting with Runway today, but it seems to me like `seo-pro` works fine after I add `seo` json column in the DB, and then add the following 3 methods on the Runway-enabled model. This assumes that you don't care about localization, but I don't think Runway is to handle localization anyway.

```
    public function locale(): string
    {
        return Config::get('app.locale');
    }

    public function in($locale): ?self
    {
        if ($this->locale() === $locale) {
            return $this;
        }

        return null;
    }

    public function status(): string
    {
        return 'published';
    }
```

**Comment by duncanmcclean** [comment]
Great!

I don't think we plan to support it *officially*. However, if you're able to get it working with some workarounds, awesome!

**Comment by dadaxr** [comment]
Just to say : I, also, was disappointed to see seo pro does not supports runway resources, given both are "first party" extension, and seo pro is a paying one.

thanks to @amadeann , I also figured out how to make it partially works with Statamic 6.

I just had to adapt this : 

```
public function locale(): ?string
{
        //this fallback to Site::current()->handle(); @see vendor/statamic/seo-pro/src/Tags/SeoProTags.php function metadata() (line 44)
        return null;
}
```

And then I've manually add the "seo pro" field in my runway ressource blueprint.

However, I tried to programmatically add the missing "seo previews" field, but it fails because it needs the entry to to be a "classic" statamic entry (ie fetchable throught Data::find )  

Also, there is no way to set default values for a given ressource, as it's possible with "section defaults"
