### ISSUE TITLE
Pretty titles not showing for fields

### ISSUE THREAD

**Issue by lukeagsmith** [statamic/seo-pro#43]
In the first versions of the addon (and as per the screenshots on Marketplace), the list of fields in the select box to set for a property showed the pretty `display:` value for the field. It now shows the file name which is not always as helpful.

In a discussion with Jack, he said this was a bug (at the same point as diagnosing asset fields not showing in the field list), but I don't think it was ever recorded. It would be nice to see the label again rather than the fieldname.

In addition, because the list of fields is seemingly drawn from across different fieldsets, it would be helpful to show which fieldset it was being drawn from for cases where there are similarly named fields.

**Comment by jasonvarga** [comment]
We changed it on purpose because it was a bit of an awkward situation.

When we used fieldset groupings, we found it was awkward to see unrelated fieldsets. You may have needed to scroll down too far to find the one you wanted.

When we used field display names, you would either see duplicates if you used the same name in multiple fieldsets:

![image](https://user-images.githubusercontent.com/105211/47656404-65267880-db65-11e8-9335-78ef27cf2f42.png)

or if we tried to add the fieldset, it just got even more messy: 

![image](https://user-images.githubusercontent.com/105211/47656440-740d2b00-db65-11e8-8345-2623783f6320.png)

If we deduplicated the fields and use the display from one of them, it could have been the least appropriate and confusing one:

![image](https://user-images.githubusercontent.com/105211/47656490-8a1aeb80-db65-11e8-939b-d6874c8b0b03.png)

So for now, we're just going to leave it as is. Maybe in v3 there will be a more natural way to deal with this.
