### ISSUE TITLE
Site Defaults Meta Description From Field and Globals

### ISSUE THREAD

**Issue by JayVerb** [statamic/seo-pro#69]
Site Defaults Meta Description "From Field" gives me a list of Globals to choose from, but nothing is populated when the page is rendered.

**Comment by jennicar** [comment]
Experienced this same bug. I have the default meta description pulling from a global field. However, all pages that are inheriting from the default meta description get nothing. A workaround for me was to choose custom and paste in the text.

**Comment by jasonvarga** [comment]
What's the use case for wanting to put globals in there?

**Comment by jasonvarga** [comment]
What's the use case for wanting to put globals in there?

Those defaults are intended to be the field for what you'd see when visiting a particular item's URL. eg. if you chose `description`, an entry's `description` field would be used.

If you were to rendering a global in there, you'd end up with the same meta description on multiple URLs.

**Comment by jennicar** [comment]
Hey, we were launching a site and wanted a default description until our
client provided us with content. I get what you’re saying though.

**Comment by jasonvarga** [comment]
In that case, I think pasting in a chunk of custom text was the right move.

**Comment by jesseleite** [comment]
In the next version (see https://github.com/statamic/seo-pro/commit/fd80089e5ecb02df804e05010953c989590a2fe9), you'll be able to select `Custom` and use antlers to reference global vars...

![image](https://user-images.githubusercontent.com/5187394/93247376-37984780-f75c-11ea-9c9e-8b12de7c49c1.png)

That said, I agree with Jason that you have to be careful when referencing globals, in order to keep meta unique 👍
