### ISSUE TITLE
Ability to set keywords

### ISSUE THREAD

**Issue by wautersj** [statamic/seo-pro#73]
I can't find a way to add seo keywords per page or collection item.
Is this included somewhere, or on the roadmap in the near future?

```
<meta name="keywords" content="XXX, YYY, ZZZ">
```

**Comment by jackmcdade** [comment]
We don't plan to add support for meta keywords because it's no longer a factor in SEO (as of 2009) and is a practice google has recommended people stop doing. More info:

- <https://webmasters.googleblog.com/2009/09/google-does-not-use-keywords-meta-tag.html>
- <https://yoast.com/meta-keywords/>

If you need keywords for a _non-SEO_ reason, you could always just add a custom `keywords` field using the `tags` fieldtype. :)

**Comment by wautersj** [comment]
Oke, got it! - I'll pass on the information to the marketing guy
